function escapePdfText(value) {
    return String(value)
        .replace(/\\/g, '\\\\')
        .replace(/\(/g, '\\(')
        .replace(/\)/g, '\\)');
}

function wrapText(text, maxChars) {
    const words = String(text || '').trim().split(/\s+/).filter(Boolean);
    if (!words.length) return [''];
    const lines = [];
    let current = words[0];

    for (let i = 1; i < words.length; i++) {
        const next = `${current} ${words[i]}`;
        if (next.length > maxChars) {
            lines.push(current);
            current = words[i];
        } else {
            current = next;
        }
    }
    lines.push(current);
    return lines;
}

function pushParagraph(target, text, opts = {}) {
    const {
        bold = false,
        maxChars = 92,
        indent = 0,
        bullet = null,
    } = opts;
    const segments = String(text || '').split('\n');
    for (const segment of segments) {
        const trimmed = segment.trim();
        if (!trimmed) {
            target.push({ kind: 'spacer', gap: 7 });
            continue;
        }
        const lines = wrapText(trimmed, Math.max(20, maxChars - Math.floor(indent / 6)));
        lines.forEach((line, idx) => {
            target.push({
                kind: 'text',
                text: idx === 0 && bullet ? `${bullet} ${line}` : line,
                bold,
                indent,
                size: bold ? 11 : 10,
            });
        });
    }
}

function parseSummaryToBlocks(summary) {
    const text = String(summary || '').trim();
    const lines = text.split('\n');
    const blocks = [];
    for (const raw of lines) {
        const line = raw.trim();
        if (!line) {
            blocks.push({ kind: 'spacer', gap: 6 });
            continue;
        }
        const headingMatch = line.match(/^\*{0,2}(Situation|Priorities|Risks|Finance[\s-–]inventory trade-off)\*{0,2}\s*:?\s*$/i);
        if (headingMatch) {
            blocks.push({ kind: 'heading', text: headingMatch[1] });
            continue;
        }
        if (/^\d+[\.\)]\s+/.test(line)) {
            blocks.push({ kind: 'numbered', text: line.replace(/^\d+[\.\)]\s+/, '') });
            continue;
        }
        if (/^[-•]\s+/.test(line)) {
            blocks.push({ kind: 'bullet', text: line.replace(/^[-•]\s+/, '') });
            continue;
        }
        blocks.push({ kind: 'paragraph', text: line });
    }
    return blocks;
}

function renderPageStream(lines, pageIndex, totalPages) {
    const commands = [];
    let y = 770;
    const left = 48;

    for (const line of lines) {
        if (line.kind === 'rule') {
            commands.push(`${left} ${y} m 564 ${y} l S`);
            y -= line.gap || 10;
            continue;
        }
        if (line.kind === 'spacer') {
            y -= line.gap || 8;
            continue;
        }
        const size = line.size || 10;
        const font = line.bold ? '/F2' : '/F1';
        const x = left + (line.indent || 0);
        commands.push('BT');
        commands.push(`${font} ${size} Tf`);
        commands.push(`1 0 0 1 ${x} ${y} Tm`);
        commands.push(`(${escapePdfText(line.text)}) Tj`);
        commands.push('ET');
        y -= line.step || (line.bold ? 15 : 13);
    }

    commands.push('BT');
    commands.push('/F1 9 Tf');
    commands.push(`1 0 0 1 ${left} 24 Tm`);
    commands.push(`(Generated by Cello AI | Page ${pageIndex + 1} of ${totalPages}) Tj`);
    commands.push('ET');

    return `${commands.join('\n')}\n`;
}

function buildExecutiveBriefPdf({
    summary,
    generatedAt,
    riskCounts,
    totalRestockCost,
    topInventory,
    topPayables,
}) {
    const lines = [];
    lines.push({ kind: 'text', text: 'Hospital Inventory & Treasury Executive Report', bold: true, size: 15, step: 18 });
    lines.push({ kind: 'spacer', gap: 2 });
    lines.push({
        kind: 'text',
        text: `Generated: ${new Date(generatedAt || Date.now()).toLocaleString('en-US')}`,
        bold: false,
        size: 10,
    });
    lines.push({
        kind: 'text',
        text: `Risk bands | Critical: ${riskCounts.CRITICAL}  High: ${riskCounts.HIGH}  Medium: ${riskCounts.MEDIUM}  Low: ${riskCounts.LOW}`,
        bold: false,
        size: 10,
    });
    lines.push({
        kind: 'text',
        text: `Estimated total restock cost: INR ${Number(totalRestockCost || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`,
        bold: false,
        size: 10,
    });
    lines.push({ kind: 'spacer', gap: 8 });
    lines.push({ kind: 'rule', gap: 10 });
    lines.push({ kind: 'text', text: 'AI Executive Brief', bold: true, size: 12, step: 16 });

    const blocks = parseSummaryToBlocks(summary || 'No summary generated.');
    let number = 1;
    for (const block of blocks) {
        if (block.kind === 'heading') {
            lines.push({ kind: 'spacer', gap: 4 });
            lines.push({ kind: 'text', text: block.text, bold: true, size: 11, step: 15 });
            continue;
        }
        if (block.kind === 'numbered') {
            pushParagraph(lines, block.text, { indent: 14, bullet: `${number}.`, maxChars: 88 });
            number += 1;
            continue;
        }
        if (block.kind === 'bullet') {
            pushParagraph(lines, block.text, { indent: 14, bullet: '-', maxChars: 88 });
            continue;
        }
        if (block.kind === 'paragraph') {
            pushParagraph(lines, block.text, { maxChars: 92 });
            continue;
        }
        lines.push(block);
    }

    lines.push({ kind: 'spacer', gap: 8 });
    lines.push({ kind: 'rule', gap: 10 });
    lines.push({ kind: 'text', text: 'Top Restock Priorities', bold: true, size: 12, step: 16 });

    const inventoryRows = (topInventory || []).slice(0, 5);
    if (!inventoryRows.length) {
        lines.push({ kind: 'text', text: 'No inventory priorities available.', bold: false });
    } else {
        inventoryRows.forEach((row, index) => {
            pushParagraph(
                lines,
                `${row.name || row.id} (${row.id}) | ${row.risk} | qty ${row.ideal_qty ?? '-'} | est INR ${Number(row.est_cost_inr || 0).toLocaleString('en-IN')}`,
                { maxChars: 90, indent: 10, bullet: `${index + 1}.` }
            );
        });
    }

    lines.push({ kind: 'spacer', gap: 8 });
    lines.push({ kind: 'rule', gap: 10 });
    lines.push({ kind: 'text', text: 'Top Payables', bold: true, size: 12, step: 16 });

    const payableRows = (topPayables || []).slice(0, 5);
    if (!payableRows.length) {
        lines.push({ kind: 'text', text: 'No payable alerts available.', bold: false });
    } else {
        payableRows.forEach((row, index) => {
            pushParagraph(
                lines,
                `${row.name || row.ref || 'Payable'} | ${row.type || '-'} | ${row.risk || '-'} | INR ${Number(row.amount_inr || 0).toLocaleString('en-IN')}`,
                { maxChars: 90, indent: 10, bullet: `${index + 1}.` }
            );
        });
    }

    const pages = [];
    let currentPage = [];
    let y = 770;
    for (const line of lines) {
        const drop =
            line.kind === 'rule'
                ? (line.gap || 10)
                : line.kind === 'spacer'
                    ? (line.gap || 8)
                    : (line.step || (line.bold ? 15 : 13));
        if (y - drop < 50) {
            pages.push(currentPage);
            currentPage = [];
            y = 770;
        }
        currentPage.push(line);
        y -= drop;
    }
    if (currentPage.length) {
        pages.push(currentPage);
    }

    const objects = [];
    const pageRefs = [];
    let nextObjectId = 5;

    for (let i = 0; i < pages.length; i++) {
        const pageObjectId = nextObjectId++;
        const contentObjectId = nextObjectId++;
        pageRefs.push(`${pageObjectId} 0 R`);

        const stream = renderPageStream(pages[i], i, pages.length);
        const length = Buffer.byteLength(stream, 'utf8');

        objects[pageObjectId] =
            `${pageObjectId} 0 obj\n` +
            `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectId} 0 R >>\n` +
            `endobj\n`;

        objects[contentObjectId] =
            `${contentObjectId} 0 obj\n` +
            `<< /Length ${length} >>\n` +
            `stream\n${stream}endstream\n` +
            `endobj\n`;
    }

    objects[1] = '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n';
    objects[2] = `2 0 obj\n<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${pages.length} >>\nendobj\n`;
    objects[3] = '3 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n';
    objects[4] = '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n';

    const header = '%PDF-1.4\n';
    let body = '';
    const xref = ['0000000000 65535 f '];
    let offset = Buffer.byteLength(header, 'utf8');
    const maxObjectId = objects.length - 1;

    for (let id = 1; id <= maxObjectId; id++) {
        const content = objects[id];
        if (!content) continue;
        xref[id] = `${String(offset).padStart(10, '0')} 00000 n `;
        body += content;
        offset += Buffer.byteLength(content, 'utf8');
    }

    const xrefPosition = Buffer.byteLength(header + body, 'utf8');
    const trailer =
        `xref\n0 ${maxObjectId + 1}\n` +
        `${xref.map((line) => `${line}\n`).join('')}` +
        `trailer\n<< /Size ${maxObjectId + 1} /Root 1 0 R >>\n` +
        `startxref\n${xrefPosition}\n%%EOF\n`;

    return Buffer.from(header + body + trailer, 'utf8');
}

module.exports = { buildExecutiveBriefPdf };
